### ISSUE TITLE
Yapıkredi 3d get3dFormData dönüşü XML Hatası

### ISSUE THREAD

**Issue by ByJacoB27** [mewebstudio/laravel-pos#1]
Merhaba;

Yapıkredi pos ile test ederken 

get3dFormData() fonksiyonun da aşağıdaki hatayı alıyorum

```
{message: "String could not be parsed as XML", exception: "Exception",…}
message: "String could not be parsed as XML"
exception: "Exception"
file: "/vendor/mews/pos/src/PosNet.php"
line: 651
trace: [{file: "/vendor/mews/pos/src/PosNet.php", line: 651,…},…]
```

**Comment by ByJacoB27** [comment]
Sorun şu ki pos bilgileri yanlış olduğunda banka hatası yerine ilk mesajımda ki hata dönüyor.

**Comment by mewebstudio** [comment]
Merhaba.

Muhtemelen bilgiler yanlış olduğu için bir xml cevabı dönmüyor. PosNet, sistem olarak biraz ilginç. Paketi dökümanlardan yola çıkarak geliştirsekte beklenmeyen çok farklı cevaplar dönebiliyor sistem. Her şeyi uygun yaptıysanız çalışmaması için bir sebep yok. Şu an 3 farklı projede kullanılıyor.

Test ortamı için de gerçek bir mağazanın bilgileri elinizde olmalı ve sisteme IP adresinizi tanımlatmalısınız.
