### ISSUE TITLE
3D İçin Örnek Döküman

### ISSUE THREAD

**Issue by muratsaglik** [mewebstudio/laravel-pos#18]
3d aşağıdaki şekilde gönderdiğimde Undefined index: HASHPARAMS hatası alıyorum. 3d için bir örnek döküman ekleyebilir misiniz?

$pos->account([
    'bank'          => 'isbank',
    'model'         => '3d',
    'client_id'     => 'XXXXX',
    'username'      => 'XXXXX',
    'password'      => 'XXXXX',
    'store_key'      => 'XXXXX',
    'env'           => '',
]);

**Comment by mewebstudio** [comment]
Merhaba, örnekler temel pos paketindeki ([https://github.com/mewebstudio/pos](url)) **examples** dizininde mevcut: [https://github.com/mewebstudio/pos/tree/master/examples](url)
