### ISSUE TITLE
PosNet.php $this->data->approved  non-object hatası mcrypt_encrypt problemi

### ISSUE THREAD

**Issue by ByJacoB27** [mewebstudio/laravel-pos#2]
PosNet.php dosyasında

>         $this->crypt = function_exists('mcrypt_encrypt') ?
>             new PosNetCrypt :
>             null;
 $this->crypt  karşılığı sunucuda mcrypt_encrypt yoksa null bırakılmış buda diğer işlemlerin aksamasına sebep oluyor ve $this->data->approved  non-object hatasına sebebiyet veriyor. null yerine bir hata fırlatılsa daha iyi olur. Read.me dosyasında minimum gereksinim kısmına da bilgi amaçlı eklenebilir.

**Comment by mewebstudio** [comment]
YapıKredi PosNet mcrypt eklentisine bağımlı, sunucunuza mcrypt kurmanız gerekiyor.
