### ISSUE TITLE
Laravel 7.0, guzzle "guzzlehttp/guzzle": "^7.3"  versiyon sorunu

### ISSUE THREAD

**Issue by blackWhaleDev** [mewebstudio/laravel-pos#21]
mews/pos[0.4.3, ..., 0.4.10] require guzzlehttp/guzzle ^6.3.3 -> found guzzlehttp/guzzle[6.3.3, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.3).

**Comment by GurrKhoo** [comment]
kardeşim yardımcı olmuyorlar, laravel 5/6/7/8 uyumlu yazmışlar ama laravel 8 kuran adam doğal olarak guzzlenin güncel verisiyonunuda kurmuş oluyor, guzzlenin güncel versiyonuna uyumlu değilse nasıl laravelin güncel versiyonuna uyumlu oluyor onuda anlayamıyorum :)

**Comment by GurrKhoo** [comment]
Adım 1
`composer remove guzzlehttp/guzzle`

Adım 2
`composer require guzzlehttp/guzzle:6.3.3`

Adım 3
`composer require mews/laravel-pos`

**Comment by blackWhaleDev** [comment]
@GurrKhoo thank you 
but I don't want to downgrade my guzzle

**Comment by nuryagdym** [comment]
fixed on v1.0.0
