### ISSUE TITLE
est 3dpay modelinde pos->payment(); metodu çalıştırıldığında Undefined index: AuthCode hatası

### ISSUE THREAD

**Issue by emredusmez** [mewebstudio/laravel-pos#25]
Akbank, ziraat v.s est entegrasyonlarda  pos->payment(); çalıştırıldığında bankadan gelen parametreler içerisinde  "AuthCode" değerini arıyor fakat böyle bir parametre gelmiyor.  createPayForAccount kullanıldığında sadece geliyor ve sorunsuz çalışıyor fakat createEstPosAccount fonksiyonunda oluşturulan request içerisinde olmayan parametreyi arıyor.

**Comment by nuryagdym** [comment]
v1.0.0 versiyona cozuldu
