### ISSUE TITLE
"System based initialization problem. Please try again later" hatası döndürüyor nedeni nedir? Ne yapmalıyım?

### ISSUE THREAD

**Issue by FatihKaya-kafgame** [mewebstudio/laravel-pos#3]
Merhaba sistemi kurup test etmek için çalıştırdım fakat belirttiğim hatayı verdi, en sona yazılan dd($payment->response) kodunu çalıştırdı yani,  ekranda sadece return code 99 vs. yazıyor. İstenilen bilgilerde ilk baştaki account kısmında client_id,username vs. olan kısımda tam olarak neyleri kastettiğini anlamadığım için rastgele bilgiler yazmıştım.
Sizce sebebi bu mudur yoksa başka bir sebepten dolayı mı bu hatayı veriyor? Yardımcı olursanız sevinirim. Paylaşımınız için de teşekkürler, emeğinize sağlık :)

**Comment by mewebstudio** [comment]
Merhaba. Test ortamı için test api, production ortamı için gerçek mağaza api bilgilerine ihtiyacınız var. Bankalardan test bilgilerini edinebilirsiniz.

**Comment by yorulmazsinan** [comment]
> 
Bankadan client_id, username ve password bilgilerini elde ettim. Fakat yine de arkadaşın dediği hatayı alıyorum.

**Comment by esakarya** [comment]
aynı hatayı cancel işleminde aldım neden olabileceği hakkında bilgisi olan varmı ?
